### ISSUE TITLE
Ubuntu v4l2loopback dkms will not build on kernel 6.8

### ISSUE THREAD

**Issue by aplund** [stefanpartheym/archlinux-ipu6-webcam#72]
I tried building with the 6.8-rc2 kernel, and the v4l2loopback ubuntu branch forks from a point where strlcpy is still used.  This commit is in the 6.8 kernel, and hence the module will not compile from this branch.  The vanilla v4l2loopback does compile.

```
commit d26270061ae66b915138af7cd73ca6f8b85e6b44
Author: Kees Cook <keescook@chromium.org>
Date:   Thu Jan 18 12:31:55 2024 -0800

    string: Remove strlcpy()

    With all the users of strlcpy() removed[1] from the kernel, remove the
    API, self-tests, and other references. Leave mentions in Documentation
    (about its deprecation), and in checkpatch.pl (to help migrate host-only
    tools/ usage). Long live strscpy().

    Link: https://github.com/KSPP/linux/issues/89 [1]
    Cc: Azeem Shaikh <azeemshaikh38@gmail.com>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: Andy Whitcroft <apw@canonical.com>
    Cc: Joe Perches <joe@perches.com>
    Cc: Dwaipayan Ray <dwaipayanray1@gmail.com>
    Cc: Lukas Bulwahn <lukas.bulwahn@gmail.com>
    Cc: linux-hardening@vger.kernel.org
    Reviewed-by: Andy Shevchenko <andy.shevchenko@gmail.com>
    Signed-off-by: Kees Cook <keescook@chromium.org>
```

**Comment by stefanpartheym** [comment]
Hi @aplund,

sorry, but I think you won't have chance with this kernel. Can't speak for Ubuntu though, as I'm using Arch (btw.).
As of now, kernel version `6.7.x` is not supported (even on Arch). I suspect it'll be the same for `6.8.x`.

Added a note to the readme, that recommends using an LTS kernel. But again, no clue, if that will work on Ubuntu though.

I'll close this one, as this won't be fixed in this repo (except someone will provide a PR).

Best regards and good luck
Stefan
